### ISSUE TITLE
fatal error: 'ElastiCode/ElastiCode.h' file not found

### ISSUE THREAD

**Issue by redolivedev** [elasticode-source/cordova-plugin#1]
I'm using your plugin for Ionic 2, but I get the following error when I try to build for iOS: 

`00:02:58.610 al/x86_64/ElasticodeCordovaPlugin.o`
`00:02:58.610`
`00:02:58.610 In file included from /Users/jenkins/workspace/cp_v2_mobile_standalone_parentApp_BRANCH/platforms/ios/Zift/Plugins/com.elasticode.cordova/elasticode/ElasticodeCordovaPlugin/ElasticodeCordovaPlugin.m:1:`
`00:02:58.611 /Users/jenkins/workspace/cp_v2_mobile_standalone_parentApp_BRANCH/platforms/ios/Zift/Plugins/com.elasticode.cordova/elasticode/ElasticodeCordovaPlugin/ElasticodeCordovaPlugin.h:2:9:`
`fatal error: 'ElastiCode/ElastiCode.h' file not found`
`00:02:58.611 #import <ElastiCode/ElastiCode.h>`
`00:02:58.611         ^`
`00:02:58.611 1 error generated.`

**Comment by stomer** [comment]
Please remove the elasticode plugin, download it from here and re-install using the following command:
`cordova plugin add <PATH TO PLUGIN>`
